version: "3"

services:
  frontend:
    image: food-recipes-fe
    volumes:
      - node_modules:/app/node_modules
      - .:/app:rw
    ports: 
      - "3000:3000"
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile

volumes:
  node_modules: